const {Router}=require('express');const Review=require('../../models/Review');const ApiResponse=require('../../utils/ApiResponse');const ApiError=require('../../utils/ApiError');const asyncHandler=require('../../utils/asyncHandler');const {authenticate,requireAdmin}=require('../../middlewares/auth.middleware');const audit=require('../audit/audit.service');const env=require('../../config/env');const {applyScope}=require('../../utils/scope');const settings=require('../settings/settings.service');const integrations=require('../integrations/integrations.service');
const {parseRange,previousRange}=require('../../utils/dateRange');
const r=Router();r.use(authenticate,requireAdmin);r.get('/',asyncHandler(async(req,res)=>{const range=parseRange(req.query);const reviewedAt={ $gte:new Date(`${range.from}T00:00:00Z`), $lte:new Date(`${range.to}T23:59:59Z`) };const reviews=await Review.find(applyScope(req.auth,{reviewedAt},req.query.locationId)).sort({reviewedAt:-1}).limit(500).lean();const stop=new Set(['the','and','for','that','this','with','was','were','are','but','not','you','your','our','had','have','has','very','they','from','food','place','restaurant']);const words=new Map();for(const review of reviews.filter(x=>Number(x.rating)<=3)){for(const word of String(review.text||'').toLowerCase().match(/[a-z]{4,}/g)||[]){if(!stop.has(word))words.set(word,(words.get(word)||0)+1)}}const themes=[...words.entries()].filter(([,count])=>count>=2).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([theme,count])=>({theme,count}));const avg=reviews.length?reviews.reduce((s,x)=>s+Number(x.rating||0),0)/reviews.length:null;const priorRange=previousRange(range);const priorReviews=await Review.find(applyScope(req.auth,{reviewedAt:{$gte:new Date(`${priorRange.from}T00:00:00Z`),$lte:new Date(`${priorRange.to}T23:59:59Z`)}},req.query.locationId)).select('rating').lean();const average=a=>a.length?a.reduce((s,x)=>s+Number(x.rating||0),0)/a.length:null;const priorAvg=average(priorReviews);const summary={range,previousRange:priorRange,count:reviews.length,averageRating:avg,urgentCount:reviews.filter(x=>Number(x.rating)<=2).length,themes,ratingMovement:reviews.length>=3&&priorReviews.length>=3?avg-priorAvg:null,sampleQualification:reviews.length<3?'Low current-period review volume':priorReviews.length<3?'Insufficient prior-period review volume':'Comparable period sample available'};ApiResponse.send(res,{data:{reviews,summary}})}));
r.post('/:id/draft-ai',asyncHandler(async(req,res)=>{
  const rev=await Review.findOne(applyScope(req.auth,{_id:req.params.id}));if(!rev)throw new ApiError(404,'Review not found');
  if(!env.openaiApiKey)throw new ApiError(503,'OpenAI is not configured');
  const tone=await settings.getEffective(req.auth.organizationId,'reviewBrandTone',rev.locationId)||'Warm, concise, professional';
  const prompt=`Draft a Google Business Profile review reply. Tone: ${tone}\nRating: ${rev.rating}/5\nReviewer: ${rev.reviewerName||'Guest'}\nReview: ${rev.text||'(no written comment)'}\nReturn only the reply text. Do not invent facts, offers, discounts, names, or contact details.`;
  const rr=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${env.openaiApiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.openaiModel,input:prompt,max_output_tokens:220})});
  const data=await rr.json();if(!rr.ok)throw new ApiError(502,`AI review draft failed: ${data.error?.message||rr.status}`);
  const text=String(data.output_text||data.output?.flatMap?.(x=>x.content||[]).map?.(x=>x.text||'').join('')||'').trim();if(!text)throw new ApiError(502,'AI returned an empty review draft');
  rev.replyText=text;rev.replyStatus='draft';rev.approvedText='';rev.approvedBy=null;rev.approvedAt=null;await rev.save();
  ApiResponse.send(res,{data:{review:rev}})
}));
r.patch('/:id/draft',asyncHandler(async(req,res)=>{const rev=await Review.findOne(applyScope(req.auth,{_id:req.params.id}));if(!rev)throw new ApiError(404,'Review not found');rev.replyText=String(req.body.text||'').trim();rev.replyStatus=rev.replyText?'draft':'none';rev.approvedText='';rev.approvedBy=null;rev.approvedAt=null;await rev.save();ApiResponse.send(res,{data:{review:rev}})}));
r.post('/:id/approve',asyncHandler(async(req,res)=>{const rev=await Review.findOne(applyScope(req.auth,{_id:req.params.id}));if(!rev)throw new ApiError(404,'Review not found');if(!rev.replyText?.trim())throw new ApiError(400,'Draft reply is required');rev.approvedText=rev.replyText;rev.replyStatus='approved';rev.approvedBy=req.user.id;rev.approvedAt=new Date();await rev.save();await audit.record({type:'review.reply.approve',result:'success',actorUserId:req.user.id,organizationId:req.auth.organizationId,meta:{reviewId:rev.id}});ApiResponse.send(res,{data:{review:rev}})}));
r.post('/:id/post',asyncHandler(async(req,res)=>{const rev=await Review.findOne(applyScope(req.auth,{_id:req.params.id}));if(!rev)throw new ApiError(404,'Review not found');if(rev.replyStatus!=='approved'||!rev.approvedText||rev.approvedText!==rev.replyText)throw new ApiError(409,'Reply must be explicitly approved after its most recent edit');if(!rev.providerLocationName)throw new ApiError(409,'Review provider location is missing');const {token}=await integrations.getGoogleAccessToken(req.auth.organizationId);const url=`https://mybusiness.googleapis.com/v4/${rev.providerLocationName}/reviews/${rev.providerReviewId}/reply`;const provider=await fetch(url,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({comment:rev.approvedText})});if(!provider.ok){const t=await provider.text();rev.replyStatus='failed';await rev.save();throw new ApiError(502,`Google review reply failed: ${t.slice(0,250)}`)}rev.replyStatus='posted';rev.postedAt=new Date();await rev.save();await audit.record({type:'review.reply.post',result:'success',actorUserId:req.user.id,organizationId:req.auth.organizationId,meta:{reviewId:rev.id}});ApiResponse.send(res,{data:{review:rev}})}));module.exports=r;
